<?php

namespace Home\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-21 at 16:28:37.
 */
class ManageProductModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ManageProductModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //模拟登录
        session('adminLogin', 1);
        $this->object = new ManageProductModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Home\Model\ManageProductModel::createProduct
     * @todo   Implement testCreateProduct().
     */
    public function testCreateProduct()
    {
        $args = [
            "productname" => "单元测试",
            "price" => 992,
            "chargeunit" => "套",
            "stock" => 2333,
            "content" => "这是单元测试",
        ];
        $this->assertEquals(0, $this->object->createProduct($args)->result);
    }

    /**
     * @covers Home\Model\ManageProductModel::searchProduct
     * @todo   Implement testSearchProduct().
     */
    public function testSearchProduct()
    {
        $args = [
            "pageindex" => 0,
            "pagesize" => 0,
        ];
        $this->assertGreaterThanOrEqual(0, $this->object->searchProduct($args)->count);
    }

    /**
     * @covers Home\Model\ManageProductModel::setUse
     * @todo   Implement testSetUse().
     */
    public function testSetUse()
    {
        $args = [
            "productid" => 1,
        ];
        $this->assertEquals(0, $this->object->setUse($args)->result);
    }

    /**
     * @covers Home\Model\ManageProductModel::setNoUse
     * @todo   Implement testSetNoUse().
     */
    public function testSetNoUse()
    {
        $args = [
            "productid" => 1,
        ];
        $this->assertEquals(0, $this->object->setNoUse($args)->result);
    }

    /**
     * @covers Home\Model\ManageProductModel::deleteProduct
     * @todo   Implement testDeleteProduct().
     */
    public function testDeleteProduct()
    {
        $args = [
            "productid" => 1,
        ];
        $this->assertEquals(0, $this->object->deleteProduct($args)->result);
    }

}
