<?php

namespace Home\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-18 at 22:29:02.
 */
class ManageProductModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ManageProductModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ManageProductModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Home\Model\ManageProductModel::createProduct
     * @todo   Implement testCreateProduct().
     */
    public function testCreateProduct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
