<?php

namespace Home\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-20 at 16:14:22.
 */
class ProductModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ProductModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ProductModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Home\Model\ProductModel::searchProduct
     * @todo   Implement testSearchProduct().
     */
    public function testSearchProduct()
    {
        $args = [
            "productname" => "",
            "byprice" => 1,
            "bysales" => 0,
            "pageindex" => 0,
            "pagesize" => 12,
        ];
        $this->assertGreaterThanOrEqual(0, $this->object->searchProduct($args)->count);
    }

    /**
     * @covers Home\Model\ProductModel::productDetail
     * @todo   Implement testProductDetail().
     */
    public function testProductDetail()
    {
        $args['productid'] = 1;
        $this->assertTrue(is_array($this->object->productDetail($args)));
    }

}
