<?php

namespace Home\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-18 at 22:30:46.
 */
class UserModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var UserModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //模拟登录
        session("login",5);
        
        $this->object = new UserModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Home\Model\UserModel::editUserInfo
     * @todo   Implement testEditUserInfo().
     */
    public function testEditUserInfo()
    {
        $args = [
            "realname" => '郝瀚',
            "idcard" => '123456789012345678',
            "address1" => "neijiang",
            "icon" => "me.png",
            "email" => "haohan@126.com",
            "birthdate" => '1993-12-18'
        ];
        $result = $this->object->editUserInfo($args);
        $this->assertGreaterThanOrEqual(0,$result->result);
    }

}
